### ISSUE TITLE
List sent and received transactions

### ISSUE THREAD

**Issue by bennyhodl** [synonymdev/react-native-ldk#114]
I don't see a way of retrieving transactions.

My guess is payments will be stored to disk for retrieval?

**Comment by Jasonvdb** [comment]
There currently is no way to list txs, LDK only deals with latest channel state. Currently in Bitkit we're just storing the tx list as part of the application state.

But I like the idea of react-native-ldk handling this as it'll make it simpler for developers. Maybe an sqlite DB or something would work.

**Comment by Jasonvdb** [comment]
Feature added here https://github.com/synonymdev/react-native-ldk/pull/136
