### ISSUE TITLE
Setting up lib environment

### ISSUE THREAD

**Issue by bennyhodl** [synonymdev/react-native-ldk#134]
Is there any documentation for setting up the `ios/` and `android/` dev environments?

**Comment by coreyphillips** [comment]
Instructions on how to setup react-native-ldk for testing can be found [here](https://github.com/synonymdev/react-native-ldk/blob/master/example/README.md).

Do you need help with anything more specific?

**Comment by ovitrif** [comment]
@bennyhodl Android/Kotlin side should work now by simply opening `lib/android` in Android Studio.

The only requirement that still stands is to have been already ran `yarn install` / `npm i` inside the `example/` folder.

@bennyhodl Is there anything else you may need here, of I can close the issue? Thanks 🙇🏻

**Comment by ovitrif** [comment]
I'm closing this for now, can always be reopened if more info is needed.
