### ISSUE TITLE
Add bolt11 invoice string to sent/claimed stored payments

### ISSUE THREAD

**Issue by Jasonvdb** [synonymdev/react-native-ldk#156]

**Comment by ovitrif** [comment]
I discussed the scope of this task with @Jasonvdb and my current understanding is that we want to add the bolt11 invoice string to the `payments_sent` persisted file.

I looked into `LDK` documentation ([invoices](https://docs.rs/lightning-invoice/latest/lightning_invoice/) and [channel manager events](https://docs.rs/lightning/0.0.121/lightning/events/enum.Event.html)) and the only place where we know the invoice string as I understand is when we pay for one.

**Comment by ovitrif** [comment]
In bitkit:
See `store/utils/lightning.ts`
//TODO remove temp hack when this is complete and descriptions/bolt11 can be added from stored tx: https://github.com/synonymdev/react-native-ldk/issues/156
