### ISSUE TITLE
Event callback value for channel_manager_channel_closed formatted incorrectly 

### ISSUE THREAD

**Issue by pwltr** [synonymdev/react-native-ldk#211]
The event callback value for `EEventTypes.channel_manager_channel_closed` does not contain the expected data. For the `reason` field it presumably should be a string or a variant of [ClosureReason](https://docs.rs/lightning/latest/lightning/events/enum.ClosureReason.html#). On Android the value for `user_channel_id` also needs to be updated.

```js
ldk.onEvent(EEventTypes.channel_manager_channel_closed, (event) => {
  console.log({ event });
);
```

Android:
```
{
  "channel_id": "f1e11600770492331f663f506d899a90d584aac15b379e978e68de0b4c633677",
  "reason": "0400",
  "user_channel_id": "org.ldk.util.UInt128@89ccf3e"
}
```

iOS:
```
{
  "channel_id": "c24e6d00428fd50c5e8800f209b2bb0ad61c34fa847ced6b74c81d60400a13e3",
  "reason": "0400",
  "user_channel_id": "0afc22b8dd66616dbe75283a802b99a7"
}
```

**Comment by ovitrif** [comment]
Integrated in bitkit:
 - https://github.com/synonymdev/bitkit/pull/1587

Moving this to "Done" since it will be tested in Bitkit via the linked PR.
