### ISSUE TITLE
Ldk does not restore LN channel with custom peer after wallet restore

### ISSUE THREAD

**Issue by limpbrains** [synonymdev/react-native-ldk#259]
I can now see that peer is recovered. lm.getPeers() returns it, peers.json has it.
But LDK does not connect to it.
Before restoring I was able to see
```
LOG  DEBUG (JS): addPeer() success. {"pubKey":"03601dd59700ee988d1b5aa2602198a5ec18321edc61ec94798fc56289f48eceae","address":"127.0.0.1","port":9735,"timeout":1000}
```
After restoring I don't see it.

Channel state becoms is_ready = false 

Because of this error bitkit e2e tests are [failing here](https://github.com/synonymdev/bitkit/pull/2051)

**Comment by ovitrif** [comment]
If I understand correctly this should be addressed once the linked issue in Bitkit repo assigned to @Jasonvdb is working?!

**Comment by Jasonvdb** [comment]
@limpbrains it was a Bitkit bug it seems, fix is here https://github.com/synonymdev/bitkit/pull/2199
