### ISSUE TITLE
Channel `is_usable` is false after app goes into background (tcp socket disconnects)

### ISSUE THREAD

**Issue by tanx** [synonymdev/react-native-ldk#56]
iOS disconnects tcp connections every time the app goes to the background. This causes the channel `is_usable` to go `false`. Perhaps one solution would be for the react-native module to detect this on the swift layer and reconnect the tcp socket when the app goes back into the foreground? The other solution would be to restart the node in the app layer when the app goes back into the foreground. See also the discord discussion here: https://discord.com/channels/915026692102316113/1029436229684580443/1030049187091451965

**Comment by coreyphillips** [comment]
Resolved as of c1d024b6b3979edfcac0d55f431ba4fa200d981c
